RetBathy=GRID_LaplacianSelectSmooth_rx0(MSK, Hobs, rx0max);
NewBathy=GRID_LinearProgrammingSmoothing_rx0_blockconstraint(...
    MSK, Hobs, rx0max, ListVal, ListBlock);
NewBathy=GRID_LinearProgrammingSmoothing_rx0_fixed(...
    MSK, Hobs, PRS, rx0max);
TheNewBathy=GRID_LinProgHeuristic_rx0_fixed(...
    MSK_rho, DEP_rho, PRS_rho, rx0max);
NewBathy=GRID_LinearProgrammingSmoothing_rx0(...
    MSK, Hobs, rx0max, SignConst, AmpConst);
NewBathy=GRID_LinearProgrammingSmoothing_rx0_similarity(...
    MSK, Hobs, rx0max, SignConst, AmpConst, MaxSimilarity);
NewBathy=GRID_LinearProgrammingSmoothing_rx0_simple(...
    MSK, Hobs, rx0max);
NewBathy=GRID_LinearProgrammingSmoothing_rx0_volume(...
    MSK, Hobs, rx0max, AreaMatrix);
[NewBathy, TotalHmodif]=GRID_LinProgSmoothVertVert_rx0(...
    MSK_rho, Hobs, rx0max, AreaMatrix);
[RetBathy, HmodifVal, ValueFct]=GRID_PlusMinusScheme_rx0(...
    MSK, Hobs, rx0max, AreaMatrix);
NewBathy=GRID_ScaledLinearProgrammingSmoothing_rx0(...
    MSK, Hobs, rx0max, SignConst, AmpConst);
NewBathy=GRID_ScaledLinearProgrammingSmoothing_rx0_simple(...
    MSK, DEP, rx0max);
RetBathy=GRID_SmoothNegative_rx0(MSK, Hobs, rx0max);
RetBathy=GRID_SmoothPositive_ROMS_rx1(...
    MSK_rho, Hobs, rx1max, ARVD);
RetBathy=GRID_SmoothPositive_rx0(MSK, Hobs, rx0max);
RetBathy=GRID_SmoothPositiveVolume_rx0(MSK, Hobs, rx0max, AreaMatrix);
TheNewBathy=GRID_LinProgHeuristic(MSK_rho, DEP_rho, rx0max);
